name: match_it
description: "Match It Game"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/modes/
    - assets/images/modes/avatars/
    - assets/images/modes/fruits/
